baseURL = "http://funderfulworld.com/"
title = "FunderfulWorld"
subtitle = "Travel blog of an Indian family"
languageCode = "en-us"
# preservetaxonomynames = true
theme = "travelify-theme"
DisqusShortname = "funderfulworld-com"

    
[params]
    # Tell me who you are

    bio = "Blogger - Programmer - Gopher"
    location = "Earth"
    site_description = "Travel blog of an Indian family"
    copyright  = "Copyright © 2017 [FunderfulWorld](http://funderfulworld.com). Powered by [Hugo](//gohugo.io). Original theme by [Colorlib](http://colorlib.com/wp/travelify/) adapted for Hugo by [Dr. Bala Ramadurai](http://balaramadurai.net)."
    avatar = "css/images/avatar.png"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "January 02, 2006"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.


[[menu.main]]
    name  = "About"
    url   = "/about-2"
    weight = 10
    
[[menu.main]]
    name  = "Contact"
    url   = "/contact/"
    weight = 20

[[menu.main]]
    name  = "Pune"
    url   = "/category/pune/"
    weight = 30

[[menu.main]]
    name  = "TheTravelBug"
    url   = "/category/thetravelbug/"
    weight = 40

[[menu.main]]
    parent = "TheTravelBug"
    name  = "Asia"
    url   = "/categories/asia/"
[[menu.main]]
    parent = "Asia"
    name  = "India"
    url   = "/categories/india/"
[[menu.main]]
    parent = "Asia"
    name  = "Thailand"
    url   = "/categories/thailand/"
    [[menu.main]]
    parent = "Asia"
    name  = "UAE"
    url   = "/categories/uae/"
    
[[menu.main]]
    parent = "TheTravelBug"
    name   = "Europe"
    url    = "/categories/europe/"
[[menu.main]]
    parent = "Europe"
    name   = "Austria"
    url    = "/categories/austria/"
[[menu.main]]
    parent = "Europe"
    name   = "Belgium"
    url    = "/categories/belgium/"
[[menu.main]]
    parent = "Europe"
    name   = "France"
    url    = "/categories/france/"
[[menu.main]]
    parent = "Europe"
    name   = "Germany"
    url    = "/categories/germany/"
[[menu.main]]
    parent = "Europe"
    name   = "Italy"
    url    = "/categories/italy/"
[[menu.main]]
    parent = "Europe"
    name   = "Luxembourg"
    url    = "/categories/luxembourg/"
[[menu.main]]
    parent = "Europe"
    name   = "Poland"
    url    = "/categories/poland/"
[[menu.main]]
    parent = "Europe"
    name   = "Switzerland"
    url    = "/categories/switzerland/"

[[menu.main]]
    parent = "TheTravelBug"
    name  = "North America"
    url   = "/categories/north-america-thetravelbug/"
[[menu.main]]
    parent = "North America"
    name  = "USA"
    url   = "/categories/north-america-thetravelbug/usa"
    
[[menu.main]]
    name = "Older Travel Tales"
    url  = "/categories/older-travel-tales-2010-and-earlier/"
    weight = 50

[[menu.main]]
    name = "Reflections"
    url  = "/categories/reflections/"
    weight = 60
   
[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = ""
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    feed            = "http://funderfulworld.com/feed/"
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "https://www.facebook.com/ItsAFunderfulWorld"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "aladybirdblogs"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    archives = false
    facebook_like = true
    search = true

[params.slider]
enable = true
num_features = 6

## DONE - Menu
## DONE - Share under each article
## DONE - Search box
## DONE - slider 
## DONE - facebook like on homepage
## TODO - category URL to work
## DONE - footer
## TODO - add tags to the footer
